---
- name: Install packages
  become: yes
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - acl
    - curl
    - python3
    - python3-dev
    - python3-pip
    - libjpeg8-dev
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - git
    - pdftk

- name: Install pip packages
  become: yes
  pip: name={{ item }} state=latest executable=pip3
  with_items:
    - virtualenv
    - pip
