---
- name: Install backend packages
  become: yes
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - nginx
    - supervisor

- name: Remove original nginx config
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: Create nginx site
  become: yes
  template:
    src: nginx.conf.jinja2
    dest: "/etc/nginx/sites-available/{{ project_name }}.conf"
    force: yes
  notify: restart nginx

- name: Enable nginx sites
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ project_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    state: link
  notify: restart nginx

- name: Create static directory
  become: yes
  file:
    path: "{{ django_static_root }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_ssh_user }}"

- name: Collect static files
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}/app"
    virtualenv: "{{ venv_path }}"
  environment: "{{ django_env }}"

- name: Create supervisor log directory
  become: yes
  file:
    path: /var/log/supervisor
    state: directory
    mode: 0755

- name: Create supervisor config
  become: yes
  template:
    src: supervisor.conf.jinja2
    dest: "/etc/supervisor/conf.d/{{ project_name }}.conf"
    force: yes

- name: Restart supervisor app
  become: yes
  supervisorctl: name="{{ project_name }}" state=restarted
